---- Base app schema

-- User
create table "user" (
 id BigInt generated by default  as identity (start with 1000) primary key,
 username varchar(128) not null unique
);


-- Task
create table "task" (
 id BigInt generated by default  as identity (start with 1000) primary key,
 task varchar(256) not null
);